require 'opal'

task :default => :build

task :build do
  Opal::Processor.method_missing_enabled = true
  Opal::Processor.const_missing_enabled = false
  Opal::Processor.source_map_enabled = false
  Opal::Processor.arity_check_enabled = false
  Opal::Processor.dynamic_require_severity = :warning

  env = Opal::Environment.new
  env.append_path '.'
  env['extension-dot-block-viz'].write_to 'extension-dot-block-viz.js'
end
